vim.cmd("set expandtab")
vim.cmd("set number")
vim.cmd("set tabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set list")
vim.cmd("set listchars=tab:>-,space:·,eol:¬")
vim.cmd("set expandtab")
vim.cmd("set mouse=a")
vim.cmd("set autoindent")
vim.cmd("set ignorecase")
vim.cmd("set smartcase")
vim.cmd("set cursorline")
vim.o.scrolloff=4
